#store: results_alloc_footloose_cap_20200205.h5
#store: results_alloc_BY2018_20221220.h5
store: results_alloc_20250428.h5
#store: /Volumes/Model\ Data\ 2/vision2050/opusgit/urbansim_data/data/psrc_parcel/runs/awsmodel07/runUS2_20191125_alloc_stc/results_alloc_stc_20191125.h5
#output_directory:  run_20200210_JF
#output_directory:  run_20200210_JF_62pseudo
output_directory:  run_alloc_20250428_no_cap/indicators

base_year: 2023

# Note: for the dashboard run run_indicators.py twice, once with "years" commented out and once without. 
years_all: [2023, 2050] # for annual indicator [start_year, end_year]
#years: [2023, 2025, 2030, 2035, 2040, 2044, 2050] # if uncommented, this has priority over years_all

compute_dataset_tables: true # non-annual years 
#compute_dataset_tables: false # annual years

#new_datasets:
#    cities:
#        csv_file: cities_62pseudo.csv
#    parcels:
#        csv_file: parcels_62pseudo.csv
#        merge_with_existing: true

indicators:
    number_of_households:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv
        
    population:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv

    number_of_jobs:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv

    residential_units:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv
        
    activity_units:
        dataset: [counties, subregs, targets, controls, control_hcts]
        file_type: csv

    #building_sqft:
        #dataset: [zones, fazes, subregs, targets, cities, growth_centers]
        #file_type: csv

    nonres_sqft:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, growth_centers]
        file_type: csv

    #max_developable_capacity:
        #dataset: [zones, fazes, subregs, targets, cities, growth_centers]
        #file_type: csv

    #max_developable_nonresidential_capacity:
        #dataset: [zones, fazes, subregs, targets, cities, growth_centers]
        #file_type: csv

    #max_developable_residential_capacity:
        #dataset: [zones, fazes, subregs, targets, cities, growth_centers]
        #file_type: csv

dataset_tables:
    #DU_and_HH_by_bld_type_by_faz_by_year:
        #dataset: [fazes]
        #file_type: tab

    employment_by_aggr_sector:
        dataset: [counties, fazes, zones, targets, controls, control_hcts, subregs, cities]
        file_type: tab
        
    household_controls:
        dataset: [household_controls]
        file_type: csv
        year: [2023]
        file_name: annual_household_control_totals
        
    employment_controls:
        dataset: [employment_controls]
        file_type: csv
        year: [2023]
        file_name: annual_employment_control_totals
        
    #employment_by_sector:
        #dataset: [zones, subregs, targets, cities]
        #file_type: tab

    #persons_by_5year_age_groups:
        #dataset: [alldata]
        #file_type: csv

    #persons_by_age_groups_of_interest:
        #dataset: [alldata]
        #file_type: csv

#    regional_total_hhs_by_30_60_90_in_14dollars_groups:
#        dataset: [alldata]
#        file_type: csv

#    regional_total_hhs_by_new_14incomegroups:
#        dataset: [alldata]
#        file_type: csv

    #pwtyp:
        #dataset: [alldata]
        #file_type: csv

    #pptyp:
        #dataset: [alldata]
        #file_type: csv

    #eoy_vacancy_by_building_type:
        #dataset: [counties]
        #file_type: csv

    #units_and_nonres_sqft_by_building_type:
        #dataset: [counties]
        #file_type: csv

    new_buildings:
        dataset: [buildings]
        file_type: tab
        year: [2050]
        include_condition: year_built > 2023
