# Indicators settings
# This file is merged with settings.yaml when running:
#   psrc_urbansim run_indicators -c "<path to configs>"
#
# The following settings are inherited from settings.yaml:
#   data_dir, output_dir, base_year

# The store field is the results HDF5 filename, resolved relative to output_dir
# By default the store is set to the most recent run in the output_dir.
# uncomment only if you need to run indicators for a specific older run.
# store: run_alloc_20260330_jk/results_alloc_20260330.h5

# Note: for the dashboard run run_indicators twice, once with "years" commented out and once without. 
#years_all: [2023, 2050] # for annual indicator [start_year, end_year]
years: [2023, 2025, 2030, 2035, 2040, 2044, 2050] # if uncommented, this has priority over years_all

compute_dataset_tables: true # annual years 
# compute_dataset_tables: false # non-annual years

#new_datasets:
#    cities:
#        csv_file: cities_62pseudo.csv
#    parcels:
#        csv_file: parcels_62pseudo.csv
#        merge_with_existing: true

indicators:
    number_of_households:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv
        
    population:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv

    number_of_jobs:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv

    residential_units:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, alldata, growth_centers]
        file_type: csv
        
    activity_units:
        dataset: [counties, subregs, targets, controls, control_hcts]
        file_type: csv

    building_sqft:
        dataset: [zones, fazes, subregs, cities, growth_centers, controls]
        file_type: csv

    nonres_sqft:
        dataset: [counties, zones, fazes, subregs, targets, controls, control_hcts, cities, growth_centers]
        file_type: csv

    max_developable_capacity:
        dataset: [zones, fazes, subregs, cities, growth_centers, controls]
        file_type: csv
        year: [2023]

    max_developable_nonresidential_capacity:
        dataset: [zones, fazes, subregs, cities, growth_centers, controls]
        file_type: csv
        year: [2023]

    max_developable_residential_capacity:
        dataset: [zones, fazes, subregs, cities, growth_centers, controls]
        file_type: csv
        year: [2023]

dataset_tables:
    #DU_and_HH_by_bld_type_by_faz_by_year:
        #dataset: [fazes]
        #file_type: tab

    employment_by_aggr_sector:
        dataset: [counties, fazes, zones, targets, controls, control_hcts, subregs, cities]
        file_type: tab
        
    household_controls:
        dataset: [household_controls]
        file_type: csv
        year: [2023]
        file_name: annual_household_control_totals
        
    employment_controls:
        dataset: [employment_controls]
        file_type: csv
        year: [2023]
        file_name: annual_employment_control_totals
        
    #employment_by_sector:
        #dataset: [zones, subregs, targets, cities]
        #file_type: tab

    #persons_by_5year_age_groups:
        #dataset: [alldata]
        #file_type: csv

    #persons_by_age_groups_of_interest:
        #dataset: [alldata]
        #file_type: csv

#    regional_total_hhs_by_30_60_90_in_14dollars_groups:
#        dataset: [alldata]
#        file_type: csv

#    regional_total_hhs_by_new_14incomegroups:
#        dataset: [alldata]
#        file_type: csv

    #pwtyp:
        #dataset: [alldata]
        #file_type: csv

    #pptyp:
        #dataset: [alldata]
        #file_type: csv

    #eoy_vacancy_by_building_type:
        #dataset: [counties]
        #file_type: csv

    #units_and_nonres_sqft_by_building_type:
        #dataset: [counties]
        #file_type: csv

    new_buildings:
        dataset: [buildings]
        file_type: tab
        year: [2050]
        include_condition: year_built > 2023
