store: psrc_base_year_2023_alloc_py3.h5

control_geography_id: subreg_id

min_overfull_buildings: 0

boost_residential_density:
  filter: is_growth_center
  boost_factor: 1.25
  
boost_nonresidential_density:
  filter: is_growth_center
  boost_factor: 1.25
 
feasibility_model_CY:
  development_filter: capacity_opportunity_non_gov_relaxed
  config_file: proforma.yaml

households_transition:
  remove_columns: []
  add_columns: ["subreg_id", "county_id"] # non-local (computed) columns
  sampling_threshold_alloc: 0.3
  sampling_hierarchy_alloc: ["persons_max", "persons_min", "county_id", "subreg_id"]

jobs_transition:
  remove_columns: []
  add_columns: ["subreg_id", "county_id"] # non-local (computed) columns 
  sampling_threshold_alloc: 0.3
  sampling_hierarchy_alloc: ["county_id", "subreg_id"]
  
household_location_choice_model_CY:
  prediction_sample_size: 100
  
employment_location_choice_model_CY:
  prediction_sample_size: 100
  
hlcmcoef_file: hlcmcoef_opus.yaml
#hlcmcoef_file: hlcmcoef_alloc_luv.yaml
hlcmcoefCY_file: hlcmcoef_alloc_luv.yaml
